// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApmGcTGvpohMAqoBPwZkDlMAbLgryOk6I',
    appId: '1:24943268871:web:34f0366223a377908e06a2',
    messagingSenderId: '24943268871',
    projectId: 'my-hospital-is-perfect',
    authDomain: 'my-hospital-is-perfect.firebaseapp.com',
    storageBucket: 'my-hospital-is-perfect.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiO94nhuFECNZzMHqo2LXyNU-DSidvAIA',
    appId: '1:24943268871:android:fd8d6a2a5e1417a28e06a2',
    messagingSenderId: '24943268871',
    projectId: 'my-hospital-is-perfect',
    storageBucket: 'my-hospital-is-perfect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX3gFMD1GghhSvBTYnEZy9zvUXn6NDMjg',
    appId: '1:24943268871:ios:ffd04797559240148e06a2',
    messagingSenderId: '24943268871',
    projectId: 'my-hospital-is-perfect',
    storageBucket: 'my-hospital-is-perfect.appspot.com',
    iosClientId: '24943268871-jmg9de1kbv414bv6l5m4gapc47dnbm67.apps.googleusercontent.com',
    iosBundleId: 'hello.com.hospitalmanagementsystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX3gFMD1GghhSvBTYnEZy9zvUXn6NDMjg',
    appId: '1:24943268871:ios:ffd04797559240148e06a2',
    messagingSenderId: '24943268871',
    projectId: 'my-hospital-is-perfect',
    storageBucket: 'my-hospital-is-perfect.appspot.com',
    iosClientId: '24943268871-jmg9de1kbv414bv6l5m4gapc47dnbm67.apps.googleusercontent.com',
    iosBundleId: 'hello.com.hospitalmanagementsystem',
  );
}
